-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.movies
(
    id serial NOT NULL,
    name text NOT NULL,
    year integer NOT NULL,
    rating numeric(2, 1) NOT NULL,
    duration integer NOT NULL,
    description text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.directors
(
    id serial NOT NULL,
    nationality_id integer,
    first_name character varying NOT NULL,
    last_name character varying,
    date_of_birth date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.actors
(
    id serial NOT NULL,
    nationality_id integer,
    first_name character varying NOT NULL,
    last_name character varying,
    date_of_birth date,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.clients
(
    id serial NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying,
    email character varying NOT NULL,
    phone character varying,
    address text,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id serial NOT NULL,
    client_id integer NOT NULL,
    movie_id integer NOT NULL,
    start_at timestamp without time zone NOT NULL,
    end_at timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.genres
(
    id serial NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.nationalities
(
    id serial NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.directors_movies
(
    director_id integer NOT NULL,
    movie_id integer NOT NULL,
    PRIMARY KEY (director_id, movie_id)
);

CREATE TABLE IF NOT EXISTS public.actors_movies
(
    actor_id integer NOT NULL,
    movie_id integer NOT NULL,
    PRIMARY KEY (actor_id, movie_id)
);

CREATE TABLE IF NOT EXISTS public.movies_genres
(
    movie_id integer NOT NULL,
    genre_id integer NOT NULL,
    PRIMARY KEY (movie_id, genre_id)
);

ALTER TABLE IF EXISTS public.directors
    ADD FOREIGN KEY (nationality_id)
    REFERENCES public.nationalities (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.actors
    ADD FOREIGN KEY (nationality_id)
    REFERENCES public.nationalities (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (movie_id)
    REFERENCES public.movies (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (client_id)
    REFERENCES public.clients (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.directors_movies
    ADD FOREIGN KEY (director_id)
    REFERENCES public.directors (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.directors_movies
    ADD FOREIGN KEY (movie_id)
    REFERENCES public.movies (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.actors_movies
    ADD FOREIGN KEY (actor_id)
    REFERENCES public.actors (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.actors_movies
    ADD FOREIGN KEY (movie_id)
    REFERENCES public.movies (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.movies_genres
    ADD FOREIGN KEY (movie_id)
    REFERENCES public.movies (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.movies_genres
    ADD FOREIGN KEY (genre_id)
    REFERENCES public.genres (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;